import type { Move } from 'chess.js';
import type { SquareKey } from '@/typings/Chessboard';

export const possibleFirstMovesWhite: Move[] = [
  {
    before: '',
    after: '',
    color: 'w',
    from: 'a2',
    to: 'a3',
    flags: 'n',
    piece: 'p',
    san: 'a3',
    lan: 'a2a3',
  },
  {
    before: '',
    after: '',
    color: 'w',
    from: 'a2',
    to: 'a4',
    flags: 'b',
    piece: 'p',
    san: 'a4',
    lan: 'a2a4',
  },
  {
    before: '',
    after: '',
    color: 'w',
    from: 'b2',
    to: 'b3',
    flags: 'n',
    piece: 'p',
    san: 'b3',
    lan: 'b2b3',
  },
  {
    before: '',
    after: '',
    color: 'w',
    from: 'b2',
    to: 'b4',
    flags: 'b',
    piece: 'p',
    san: 'b4',
    lan: 'b2b4',
  },
  {
    before: '',
    after: '',
    color: 'w',
    from: 'c2',
    to: 'c3',
    flags: 'n',
    piece: 'p',
    san: 'c3',
    lan: 'c2c3',
  },
  {
    before: '',
    after: '',
    color: 'w',
    from: 'c2',
    to: 'c4',
    flags: 'b',
    piece: 'p',
    san: 'c4',
    lan: 'c2c4',
  },
  {
    before: '',
    after: '',
    color: 'w',
    from: 'd2',
    to: 'd3',
    flags: 'n',
    piece: 'p',
    san: 'd3',
    lan: 'd2d3',
  },
  {
    before: '',
    after: '',
    color: 'w',
    from: 'd2',
    to: 'd4',
    flags: 'b',
    piece: 'p',
    san: 'd4',
    lan: 'd2d4',
  },
  {
    before: '',
    after: '',
    color: 'w',
    from: 'e2',
    to: 'e3',
    flags: 'n',
    piece: 'p',
    san: 'e3',
    lan: 'e2e3',
  },
  {
    before: '',
    after: '',
    color: 'w',
    from: 'e2',
    to: 'e4',
    flags: 'b',
    piece: 'p',
    san: 'e4',
    lan: 'e2e4',
  },
  {
    before: '',
    after: '',
    color: 'w',
    from: 'f2',
    to: 'f3',
    flags: 'n',
    piece: 'p',
    san: 'f3',
    lan: 'f2f3',
  },
  {
    before: '',
    after: '',
    color: 'w',
    from: 'f2',
    to: 'f4',
    flags: 'b',
    piece: 'p',
    san: 'f4',
    lan: 'f2f4',
  },
  {
    before: '',
    after: '',
    color: 'w',
    from: 'g2',
    to: 'g3',
    flags: 'n',
    piece: 'p',
    san: 'g3',
    lan: 'g2g3',
  },
  {
    before: '',
    after: '',
    color: 'w',
    from: 'g2',
    to: 'g4',
    flags: 'b',
    piece: 'p',
    san: 'g4',
    lan: 'g2g4',
  },
  {
    before: '',
    after: '',
    color: 'w',
    from: 'h2',
    to: 'h3',
    flags: 'n',
    piece: 'p',
    san: 'h3',
    lan: 'h2h3',
  },
  {
    before: '',
    after: '',
    color: 'w',
    from: 'h2',
    to: 'h4',
    flags: 'b',
    piece: 'p',
    san: 'h4',
    lan: 'h2h4',
  },
  {
    before: '',
    after: '',
    color: 'w',
    from: 'b1',
    to: 'a3',
    flags: 'n',
    piece: 'n',
    san: 'Na3',
    lan: 'b1a3',
  },
  {
    before: '',
    after: '',
    color: 'w',
    from: 'b1',
    to: 'c3',
    flags: 'n',
    piece: 'n',
    san: 'Nc3',
    lan: 'b1c3',
  },
  {
    before: '',
    after: '',
    color: 'w',
    from: 'g1',
    to: 'f3',
    flags: 'n',
    piece: 'n',
    san: 'Nf3',
    lan: 'g1f3',
  },
  {
    before: '',
    after: '',
    color: 'w',
    from: 'g1',
    to: 'h3',
    flags: 'n',
    piece: 'n',
    san: 'Nh3',
    lan: 'g1h3',
  },
];

export const possibleFirstThreatsWhite = [
  { orig: 'a3', brush: 'yellow' },
  { orig: 'a4', brush: 'yellow' },
  { orig: 'b3', brush: 'yellow' },
  { orig: 'b4', brush: 'yellow' },
  { orig: 'c3', brush: 'yellow' },
  { orig: 'c4', brush: 'yellow' },
  { orig: 'd3', brush: 'yellow' },
  { orig: 'd4', brush: 'yellow' },
  { orig: 'e3', brush: 'yellow' },
  { orig: 'e4', brush: 'yellow' },
  { orig: 'f3', brush: 'yellow' },
  { orig: 'f4', brush: 'yellow' },
  { orig: 'g3', brush: 'yellow' },
  { orig: 'g4', brush: 'yellow' },
  { orig: 'h3', brush: 'yellow' },
  { orig: 'h4', brush: 'yellow' },
  { orig: 'a3', brush: 'yellow' },
  { orig: 'c3', brush: 'yellow' },
  { orig: 'f3', brush: 'yellow' },
  { orig: 'h3', brush: 'yellow' },
];

export const moveableSquaresWhite: SquareKey[] = [
  'a3',
  'a4',
  'b3',
  'b4',
  'c3',
  'c4',
  'd3',
  'd4',
  'e3',
  'e4',
  'f3',
  'f4',
  'g3',
  'g4',
  'h3',
  'h4',
];
