import type { Move } from 'chess.js';
import type { SquareKey } from '@/typings/Chessboard';

export const moves: Move[] = [
  {
    color: 'b',
    from: 'b8',
    to: 'c6',
    flags: 'n',
    piece: 'n',
    san: 'Nc6',
  },
  {
    color: 'b',
    from: 'b8',
    to: 'a6',
    flags: 'n',
    piece: 'n',
    san: 'Na6',
  },
  {
    color: 'b',
    from: 'd8',
    to: 'e7',
    flags: 'n',
    piece: 'q',
    san: 'Qe7',
  },
  {
    color: 'b',
    from: 'd8',
    to: 'f6',
    flags: 'n',
    piece: 'q',
    san: 'Qf6',
  },
  {
    color: 'b',
    from: 'd8',
    to: 'g5',
    flags: 'c',
    piece: 'q',
    captured: 'q',
    san: 'Qxg5',
  },
  {
    color: 'b',
    from: 'f8',
    to: 'e7',
    flags: 'n',
    piece: 'b',
    san: 'Be7',
  },
  {
    color: 'b',
    from: 'f8',
    to: 'd6',
    flags: 'n',
    piece: 'b',
    san: 'Bd6',
  },
  {
    color: 'b',
    from: 'f8',
    to: 'c5',
    flags: 'n',
    piece: 'b',
    san: 'Bc5',
  },
  {
    color: 'b',
    from: 'f8',
    to: 'b4',
    flags: 'n',
    piece: 'b',
    san: 'Bb4',
  },
  {
    color: 'b',
    from: 'f8',
    to: 'a3',
    flags: 'n',
    piece: 'b',
    san: 'Ba3',
  },
  {
    color: 'b',
    from: 'g8',
    to: 'h6',
    flags: 'n',
    piece: 'n',
    san: 'Nh6',
  },
  {
    color: 'b',
    from: 'g8',
    to: 'f6',
    flags: 'n',
    piece: 'n',
    san: 'Nf6',
  },
  {
    color: 'b',
    from: 'g8',
    to: 'e7',
    flags: 'n',
    piece: 'n',
    san: 'Ne7',
  },
  {
    color: 'b',
    from: 'a7',
    to: 'a6',
    flags: 'n',
    piece: 'p',
    san: 'a6',
  },
  {
    color: 'b',
    from: 'a7',
    to: 'a5',
    flags: 'b',
    piece: 'p',
    san: 'a5',
  },
  {
    color: 'b',
    from: 'b7',
    to: 'b6',
    flags: 'n',
    piece: 'p',
    san: 'b6',
  },
  {
    color: 'b',
    from: 'b7',
    to: 'b5',
    flags: 'b',
    piece: 'p',
    san: 'b5',
  },
  {
    color: 'b',
    from: 'c7',
    to: 'c6',
    flags: 'n',
    piece: 'p',
    san: 'c6',
  },
  {
    color: 'b',
    from: 'c7',
    to: 'c5',
    flags: 'b',
    piece: 'p',
    san: 'c5',
  },
  {
    color: 'b',
    from: 'd7',
    to: 'd6',
    flags: 'n',
    piece: 'p',
    san: 'd6',
  },
  {
    color: 'b',
    from: 'd7',
    to: 'd5',
    flags: 'b',
    piece: 'p',
    san: 'd5',
  },
  {
    color: 'b',
    from: 'f7',
    to: 'f6',
    flags: 'n',
    piece: 'p',
    san: 'f6',
  },
  {
    color: 'b',
    from: 'f7',
    to: 'f5',
    flags: 'b',
    piece: 'p',
    san: 'f5',
  },
  {
    color: 'b',
    from: 'g7',
    to: 'g6',
    flags: 'n',
    piece: 'p',
    san: 'g6',
  },
  {
    color: 'b',
    from: 'h7',
    to: 'h6',
    flags: 'n',
    piece: 'p',
    san: 'h6',
  },
  {
    color: 'b',
    from: 'h7',
    to: 'h5',
    flags: 'b',
    piece: 'p',
    san: 'h5',
  },
  {
    color: 'b',
    from: 'h2',
    to: 'g1',
    flags: 'cp',
    piece: 'p',
    promotion: 'q',
    captured: 'n',
    san: 'hxg1=Q',
  },
  {
    color: 'b',
    from: 'h2',
    to: 'g1',
    flags: 'cp',
    piece: 'p',
    promotion: 'r',
    captured: 'n',
    san: 'hxg1=R',
  },
  {
    color: 'b',
    from: 'h2',
    to: 'g1',
    flags: 'cp',
    piece: 'p',
    promotion: 'b',
    captured: 'n',
    san: 'hxg1=B',
  },
  {
    color: 'b',
    from: 'h2',
    to: 'g1',
    flags: 'cp',
    piece: 'p',
    promotion: 'n',
    captured: 'n',
    san: 'hxg1=N',
  },
];

export const possibleFirstMovesWhite: Move[] = [
  {
    color: 'w',
    from: 'a2',
    to: 'a3',
    flags: 'n',
    piece: 'p',
    san: 'a3',
  },
  {
    color: 'w',
    from: 'a2',
    to: 'a4',
    flags: 'b',
    piece: 'p',
    san: 'a4',
  },
  {
    color: 'w',
    from: 'b2',
    to: 'b3',
    flags: 'n',
    piece: 'p',
    san: 'b3',
  },
  {
    color: 'w',
    from: 'b2',
    to: 'b4',
    flags: 'b',
    piece: 'p',
    san: 'b4',
  },
  {
    color: 'w',
    from: 'c2',
    to: 'c3',
    flags: 'n',
    piece: 'p',
    san: 'c3',
  },
  {
    color: 'w',
    from: 'c2',
    to: 'c4',
    flags: 'b',
    piece: 'p',
    san: 'c4',
  },
  {
    color: 'w',
    from: 'd2',
    to: 'd3',
    flags: 'n',
    piece: 'p',
    san: 'd3',
  },
  {
    color: 'w',
    from: 'd2',
    to: 'd4',
    flags: 'b',
    piece: 'p',
    san: 'd4',
  },
  {
    color: 'w',
    from: 'e2',
    to: 'e3',
    flags: 'n',
    piece: 'p',
    san: 'e3',
  },
  {
    color: 'w',
    from: 'e2',
    to: 'e4',
    flags: 'b',
    piece: 'p',
    san: 'e4',
  },
  {
    color: 'w',
    from: 'f2',
    to: 'f3',
    flags: 'n',
    piece: 'p',
    san: 'f3',
  },
  {
    color: 'w',
    from: 'f2',
    to: 'f4',
    flags: 'b',
    piece: 'p',
    san: 'f4',
  },
  {
    color: 'w',
    from: 'g2',
    to: 'g3',
    flags: 'n',
    piece: 'p',
    san: 'g3',
  },
  {
    color: 'w',
    from: 'g2',
    to: 'g4',
    flags: 'b',
    piece: 'p',
    san: 'g4',
  },
  {
    color: 'w',
    from: 'h2',
    to: 'h3',
    flags: 'n',
    piece: 'p',
    san: 'h3',
  },
  {
    color: 'w',
    from: 'h2',
    to: 'h4',
    flags: 'b',
    piece: 'p',
    san: 'h4',
  },
  {
    color: 'w',
    from: 'b1',
    to: 'a3',
    flags: 'n',
    piece: 'n',
    san: 'Na3',
  },
  {
    color: 'w',
    from: 'b1',
    to: 'c3',
    flags: 'n',
    piece: 'n',
    san: 'Nc3',
  },
  {
    color: 'w',
    from: 'g1',
    to: 'f3',
    flags: 'n',
    piece: 'n',
    san: 'Nf3',
  },
  {
    color: 'w',
    from: 'g1',
    to: 'h3',
    flags: 'n',
    piece: 'n',
    san: 'Nh3',
  },
];

export const possibleFirstThreatsWhite = [
  { orig: 'a3', brush: 'yellow' },
  { orig: 'a4', brush: 'yellow' },
  { orig: 'b3', brush: 'yellow' },
  { orig: 'b4', brush: 'yellow' },
  { orig: 'c3', brush: 'yellow' },
  { orig: 'c4', brush: 'yellow' },
  { orig: 'd3', brush: 'yellow' },
  { orig: 'd4', brush: 'yellow' },
  { orig: 'e3', brush: 'yellow' },
  { orig: 'e4', brush: 'yellow' },
  { orig: 'f3', brush: 'yellow' },
  { orig: 'f4', brush: 'yellow' },
  { orig: 'g3', brush: 'yellow' },
  { orig: 'g4', brush: 'yellow' },
  { orig: 'h3', brush: 'yellow' },
  { orig: 'h4', brush: 'yellow' },
  { orig: 'a3', brush: 'yellow' },
  { orig: 'c3', brush: 'yellow' },
  { orig: 'f3', brush: 'yellow' },
  { orig: 'h3', brush: 'yellow' },
];

export const moveableSquaresWhite: SquareKey[] = [
  'b1',
  'g1',
  'a2',
  'b2',
  'c2',
  'd2',
  'e2',
  'f2',
  'g2',
  'h2',
];
