name: Tests

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Use Node.js 24
        uses: actions/setup-node@v7
        with:
          node-version: 24

      - name: npm install
        run: npm ci
      - name: check code style
        run: npm run lint
      - name: run type checks
        run: npm run type-check
      - name: run tests
        run: npm run test
      - name: test build process
        run: npm run build
      - name: check package exports
        run: npx publint --strict
